spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/taskdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#Swagger details
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: metrics
  metrics:
    export:
      enabled: true 